### ISSUE TITLE
Annotating a file with unicode characters

### ISSUE THREAD

**Issue by michaeleekk** [plangrid/pdf-annotate#64]
I tried to annotate a list of files with this package. However, I found that if the files contain non-latin characters, like Japanese, the `write()` function will be failed. I wonder if this is a known issue or not ? Is there anything I need to do before annotating the files ?

Here is the traceback,

```
Traceback (most recent call last):
  File "b.py", line 39, in <module>
    add_filename(u'{}/{}'.format(directory, filename))
  File "b.py", line 31, in add_filename
    a.write(u'outs/'+filename)  # or use overwrite=True if you feel lucky
  File "/usr/local/lib/python3.7/site-packages/pdf_annotate/annotator.py", line 320, in write
    writer.write(fname=filename, trailer=self._pdf._reader)
  File "/usr/local/lib/python3.7/site-packages/pdfrw/pdfwriter.py", line 358, in write
    self.killobj, user_fmt=user_fmt)
  File "/usr/local/lib/python3.7/site-packages/pdfrw/pdfwriter.py", line 196, in FormatObjects
    format_deferred()
  File "/usr/local/lib/python3.7/site-packages/pdfrw/pdfwriter.py", line 164, in format_deferred
    objlist[index] = format_obj(obj)
  File "/usr/local/lib/python3.7/site-packages/pdfrw/pdfwriter.py", line 139, in format_obj
    do_compress([obj])
  File "/usr/local/lib/python3.7/site-packages/pdfrw/compress.py", line 23, in compress
    newstr = convert_load(zlib.compress(convert_store(oldstr)))
  File "/usr/local/lib/python3.7/site-packages/pdfrw/py23_diffs.py", line 22, in convert_store
    return s.encode('Latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 83-89: ordinal not in range(256)
```

I'm using Python 3.7.4 on MacOS, and I installed this package with pip. `pdf-annotate==0.11.0`

**Comment by ssheldonpg** [comment]
Yes this is a known issue, in order to annotate with unicode characters you have to embed a subset CID font which comes with a lot of data structures for the font characteristics.  The implementation of this was started with this library, but it was unfortunately not completed.

**Comment by HyunjiEllenPak** [comment]
@ssheldonpg 
Hi, I have same problem as he(@michaeleekk) had.
Did you find the solution that annotates unicode characters such as korean or japanese?

**Comment by ssheldonpg** [comment]
> @ssheldonpg Hi, I have same problem as he(@michaeleekk) had. Did you find the solution that annotates unicode characters such as korean or japanese?

I did end up adding most of the support for embedding unicode fonts in the PDF, but before it was fully completed we moved off of using this package and so haven't put any more time back into it.  Sorry!

**Comment by Vaibhav6200** [comment]
which package should we use in order to annotate just like pdf_annotate and which gives UTF-8 support ?
